# Generated by Django 5.2.1 on 2025-05-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("registered_date", models.DateField(auto_now_add=True)),
                ("last_login", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "Account",
                "ordering": ["id"],
                "get_latest_by": "last_login",
                "unique_together": {("username", "email")},
            },
        ),
    ]
