# Generated by Django 5.2.1 on 2025-05-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                default="accounts/default.png", upload_to="accounts/"
            ),
        ),
    ]
