# Generated by Django 5.2.1 on 2025-05-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("Buying_Date", models.DateField()),
                ("Classification", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="products/")),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["Buying_Date"],
            },
        ),
    ]
