# Generated by Django 5.2.1 on 2025-05-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_alter_product_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["Shooting_Date"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Buying_Date",
            new_name="Shooting_Date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="Classification",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
