# Generated by Django 5.2.1 on 2025-05-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
